Repository ManatiCR/retopais, pull requests merged in 2019-05, with the labels that each got.

#120 Add drush hack to allow deploy
  .circleci/config.yml
Labels: Passes Code Review, Ready to Merge

#126 footer icos + problematica intro-text format
  modules/features/retopais_feature_alliances/retopais_feature_alliances.pages_default.inc
  modules/features/retopais_feature_alliances/retopais_feature_alliances.views_default.inc
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.features.field_base.inc
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.features.field_instance.inc
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.features.inc
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.features.taxonomy.inc
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.info
  modules/features/retopais_feature_field_bases/retopais_feature_field_bases.strongarm.inc
  modules/features/retopais_feature_pages/plugins/content_types/alianzas_cta.inc
  modules/features/retopais_feature_pages/retopais_feature_pages.module
  modules/features/retopais_feature_proposals/retopais_feature_proposals.features.field_base.inc
  modules/features/retopais_feature_proposals/retopais_feature_proposals.features.field_instance.inc
  modules/features/retopais_feature_proposals/retopais_feature_proposals.field_group.inc
  modules/features/retopais_feature_proposals/retopais_feature_proposals.info
  modules/features/retopais_feature_proposals/retopais_feature_proposals.module
  modules/features/retopais_feature_proposals/retopais_feature_proposals.strongarm.inc
  modules/features/retopais_feature_proposals/retopais_feature_proposals.views_default.inc
  themes/custom/retopais/css/style.css
  themes/custom/retopais/img/icons/problematica/acceso-cultura-sm.png
  themes/custom/retopais/img/icons/problematica/acceso-cultura.png
  themes/custom/retopais/img/icons/problematica/descarbonizacion-sm.png
  themes/custom/retopais/img/icons/problematica/descarbonizacion.png
  themes/custom/retopais/img/icons/problematica/gestion-residuos-sm.png
  themes/custom/retopais/img/icons/problematica/gestion-residuos.png
  themes/custom/retopais/img/icons/problematica/seguridad-ciudadana-sm.png
  themes/custom/retopais/img/icons/problematica/seguridad-ciudadana.png
  themes/custom/retopais/sass/partials/design/_page-alianzas.scss
  themes/custom/retopais/sass/partials/design/_page-problematica.scss
  themes/custom/retopais/sass/partials/design/_page-reto-pais.scss
  themes/custom/retopais/sass/partials/design/_proposal-cta-footer.scss
Labels: Ready to Merge

#134 Fix on the field Provincia - Canton on mobile
  modules/features/retopais_feature_config/retopais_feature_config.features.user_permission.inc
  modules/features/retopais_feature_proposals/retopais_feature_proposals.features.field_instance.inc
Labels: Passes Code Review, Passes Functional Review, Ready to Merge

#138 Fix IE11 bugs
  gulp-tasks/theme.js
  package-lock.json
  package.json
  themes/custom/retopais/css/style.css
  themes/custom/retopais/sass/partials/global/_extends.scss
  themes/custom/retopais/sass/style.scss
Labels: Passes Code Review, Passes Functional Review, Ready to Merge

#135 Update SMTP mail config.
  modules/features/retopais_feature_config/retopais_feature_config.strongarm.inc
Labels: Passes Code Review, Passes Functional Review, Ready to Merge

#136 Update Drupal Core
  drupal.make.yml
Labels: Passes Code Review, Passes Functional Review, Ready to Merge
